### ISSUE TITLE
Extend metaSMT usage manual

### ISSUE THREAD

**Issue by keszocze** [agra-uni-bremen/metaSMT#16]
Right now the '## 3. Using metaSMT' part of the README.md only explains how to use
metaSMT by putting one's sourcecode directly into the metaSMT/toolbox folder. I think that
this, for most people, might not be the way they intend to use metaSMT.

I think we should add an explanation on how to use metaSMT from another project. My 
suggestion would be:
## 3. Using metaSMT

There are two methods of using metaSMT
- internally: Write your own code within the metaSMT toolbox folder
- externally: Use metaSMT with your own, probably already existing, cmake project.
### Internal project

The toolbox folder provides an easy way to use metaSMT in your own code.
Just create a subfolder and start writing a program. All C++ code will
automatically build into an executable. The folder contains a separate README
and some examples using metaSMT.
### External project

To use metaSMT with your (already existing) project you need to tell `cmake` that is should 
be looking for metaSMT. To do so, edit the main `CMakeLists.txt` file by adding the line

```
find_package( metaSMT REQUIRED )
```

You still have to tell `cmake` where to look for metaSMT by setting the `CMAKE_PREFIX_PATH`
variable, either by

```
export CMAKE_PREFIX_PATH=/path/to/metaSMT/install
cmake ...
```

or

```
cmake -DCMAKE_PREFIX_PATH=/path/to/metaSMT/install ...
```

**Comment by sfrehse** [comment]
:+1:

**Comment by finnhaedicke** [comment]
+1

I like it.

**Comment by hriener** [comment]
Me too!

Minor comments:
/that is should/that _it_ should/
/edit the main CMakeLists.txt file by adding/edit the main CMakeLists.txt file _and add_/
/the CMAKE_PREFIX_PATH variable/the variable CMAKE_PREFIX_PATH/
/cmake .../ cmake [...]/ (to distinguish it from ''cmake ..'' ;) )
