### ISSUE TITLE
CVC4 build failed

### ISSUE THREAD

**Issue by hriener** [agra-uni-bremen/metaSMT#21]
On a system without Boost, building metaSMT with CVC4 fails.

<pre>
checking for Boost headers version >= 0.0.0... no
configure: error: cannot find Boost headers version >= 0.0.0
ERROR: build_install failed for cvc4-1.4
</pre>

**Comment by finnhaedicke** [comment]
I assume this is a dependencies issue. Can you try adding `--with-boost=$root/boost-1_55_0` to `./configure` and changing dependencies to

```
dependencies="libantlr3c-3.4 boost-1_55_0"
```

**Comment by hriener** [comment]
I was not aware that you can add more than one dependency. That's amazing! Commit is on the way.
