### ISSUE TITLE
Boolector 2.0.7

### ISSUE THREAD

**Issue by hriener** [agra-uni-bremen/metaSMT#39]
End of May Boolector 2.0.7 was released: http://fmv.jku.at/boolector/

**Comment by finnhaedicke** [comment]
It needs to be added to [dependencies](https://github.com/agra-uni-bremen/dependencies), and the [boolector 2.x branch](https://github.com/finnhaedicke/metaSMT/tree/add-boolector-2.0) needs to be updated and merged.

**Comment by hoangmle** [comment]
We support Boolector 2.2.0 now
